# Ref: https://dev.to/aws-builders/containerize-react-app-with-docker-for-production-572b
# stage1 - build react app first
FROM node:lts-alpine3.15 as build
ARG SOCIAL_API_PROD=https://api.gitter.uk
WORKDIR /app
ENV REACT_APP_API_URL $SOCIAL_API_PROD
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json /app/
RUN npm install
COPY . /app
COPY keycloak.json /app/public/keycloak.json
RUN npm run build

# stage 2 - build the final image and copy the react build files
FROM nginx:1.21.6-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
